`ifdef ENABLE_SDF
		initial begin
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_1__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_2__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_3__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_4__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_5__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_6__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_7__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__0_.sdf", uut.mprj.fpga_core_uut.cbx_8__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_1__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_2__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_3__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_4__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_5__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_6__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_7__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__1_.sdf", uut.mprj.fpga_core_uut.cbx_8__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_1__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_2__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_3__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_4__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_5__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_6__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_7__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cbx_1__2_.sdf", uut.mprj.fpga_core_uut.cbx_8__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_0__1_.sdf", uut.mprj.fpga_core_uut.cby_0__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_1__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_2__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_3__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_4__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_5__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_6__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_1__1_.sdf", uut.mprj.fpga_core_uut.cby_7__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/cby_2__1_.sdf", uut.mprj.fpga_core_uut.cby_8__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__0_.sdf", uut.mprj.fpga_core_uut.sb_0__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__1_.sdf", uut.mprj.fpga_core_uut.sb_0__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__2_.sdf", uut.mprj.fpga_core_uut.sb_0__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_0__2_.sdf", uut.mprj.fpga_core_uut.sb_0__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_1__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_2__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_3__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_4__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_5__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_6__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__0_.sdf", uut.mprj.fpga_core_uut.sb_7__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_1__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_2__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_3__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_4__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_5__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_6__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__1_.sdf", uut.mprj.fpga_core_uut.sb_7__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_1__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_2__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_3__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_4__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_5__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_6__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_1__2_.sdf", uut.mprj.fpga_core_uut.sb_7__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__0_.sdf", uut.mprj.fpga_core_uut.sb_2__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__0_.sdf", uut.mprj.fpga_core_uut.sb_8__0_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__1_.sdf", uut.mprj.fpga_core_uut.sb_8__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__2_.sdf", uut.mprj.fpga_core_uut.sb_2__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/sb_2__2_.sdf", uut.mprj.fpga_core_uut.sb_8__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_1__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_2__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_3__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_4__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_5__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_6__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_7__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__1_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__2_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__3_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__4_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__5_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__6_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__7_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/grid_clb.sdf", uut.mprj.fpga_core_uut.grid_clb_8__8_) ;
            $sdf_annotate("/home/karim/work/ef/clear/sdf/tie_array.sdf", uut.mprj.fpga_core_uut.tie_array) ;
            $sdf_annotate("/home/karim/work/ef/og_litex/sdf/DFFRAM.sdf", uut.soc.DFFRAM_0) ;
            $sdf_annotate("/home/karim/work/ef/og_litex/sdf/mgmt_core.sdf", uut.soc.core) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/housekeeping.sdf", uut.housekeeping) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/chip_io.sdf", uut.padframe) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/mprj_logic_high.sdf", uut.mgmt_buffers.mprj_logic_high_inst) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/mprj2_logic_high.sdf", uut.mgmt_buffers.mprj2_logic_high_inst) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/mgmt_protect_hv.sdf", uut.mgmt_buffers.powergood_check) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/mgmt_protect.sdf", uut.mgmt_buffers) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/caravel_clocking.sdf", uut.clocking) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/digital_pll.sdf", uut.pll) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/xres_buf.sdf", uut.rstb_level) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/user_id_programming.sdf", uut.user_id_value) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_bidir_1[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_bidir_1[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_bidir_2[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_bidir_2[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_bidir_2[2] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[2] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[3] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[4] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[5] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[6] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[7] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[8] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[9] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1[10] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[2] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[3] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[4] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_1a[5] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[2] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[3] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[4] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[5] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[6] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[7] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[8] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[9] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[10] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[11] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[12] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[13] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[14] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_control_block.sdf", uut.\gpio_control_in_2[15] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.\gpio_defaults_block_0[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.\gpio_defaults_block_0[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.\gpio_defaults_block_2[0] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.\gpio_defaults_block_2[1] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.\gpio_defaults_block_2[2] ) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_5) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_6) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_7) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_8) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_9) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_10) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_11) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_12) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_13) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_14) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_15) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_16) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_17) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_18) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_19) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_20) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_21) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_22) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_23) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_24) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_25) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_26) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_27) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_28) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_29) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_30) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_31) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_32) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_33) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_34) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_35) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_36) ;
            $sdf_annotate("/home/karim/work/ef/og_caravel/sdf/gpio_defaults_block.sdf", uut.gpio_defaults_block_37) ;
        end
    `endif
